### ISSUE TITLE
[Bug] SQS Sink Connector should properly handle avro message

### ISSUE THREAD

**Issue by nlu90** [streamnative/pulsar-io-sqs#128]
**Describe the bug**
If the topic with an avro schema, the connector fails to publish a message with the following error:
```
15:09:01.753 [SQSQueueBufferWorkerThread-10] ERROR org.apache.pulsar.ecosystem.io.sqs.SQSSink - failed send message to AWS SQS.
com.amazonaws.AmazonServiceException: Invalid binary character '#x2' was found in the message body, the set of allowed characters is #x9 | #xA | #xD | [#x20-#xD7FF] | [#xE000-#xFFFD] | [#x10000-#x10FFFF]. (Service: AmazonSQS; Status Code: 0; Error Code: InvalidMessageContents; Request ID: null)
	at com.amazonaws.services.sqs.buffered.ResultConverter.convert(ResultConverter.java:37) ~[aws-java-sdk-sqs-1.11.106.jar:?]
	at com.amazonaws.services.sqs.buffered.SendQueueBuffer$SendMessageBatchTask.process(SendQueueBuffer.java:522) ~[aws-java-sdk-sqs-1.11.106.jar:?]
	at com.amazonaws.services.sqs.buffered.SendQueueBuffer$OutboundBatchTask.run(SendQueueBuffer.java:443) ~[aws-java-sdk-sqs-1.11.106.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**To Reproduce**
1. Create a topic with avro message
2. Run the sink connector

**Expected behavior**
The message should be converted to json format string and be published into sqs queue.

**Comment by Huanli-Meng** [comment]
@nlu90 Does this PR need to update the doc accordingly? Thanks.
